import { OrbitControls, Sparkles } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100svh] bg-black">
        <Canvas>
          <ambientLight />
          <Sparkles
            count={1000}
            speed={0}
            opacity={1}
            color="white"
            size={5}
            scale={77}
            noise={1}
          />
          <OrbitControls />
        </Canvas>
      </main>
    </>
  );
};

export default Home;
